apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels:
    run: gop-fileserver
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: normal
  hostPath:
    path: "/web"
  