---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: data-pv
    labels:
      app: gop-fileserver
spec:
   accessModes: ["ReadWriteMany"]
   capacity:
    storage: 1Gi
   hostPath:
      path: /web
      type: DirectoryOrCreate
  
