apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  labels:
    run: gop-fileserver
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: normal
  selector:
    matchLabels:
      run: gop-fileserver