---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: data-pvc
    labels:
      app: gop-fileserver
spec:
   accessModes:
   - ReadWriteMany
   resources:
    requests:
       storage: 1Gi
   selector:
    matchLabels:
      app: gop-fileserver