apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    app: drupal
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:                # drupal-pv with hostPath
    path: "/drupal-data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  labels:
    app: drupal-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:                # drupal-mysql-pv with hostPath
    path: "/drupal-mysql-data"
    type: DirectoryOrCreate