kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "drupal"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "drupal-mysql"
