apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-04-25T12:08:18Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: jekyll-site
  resourceVersion: "1687"
  selfLink: /api/v1/persistentvolumes/jekyll-site
  uid: ebd6a5e6-a5be-11eb-8499-0242ac11001a
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jekyll-site
    namespace: development
    resourceVersion: "1684"
    uid: 5133868a-a5c0-11eb-8499-0242ac11001a
  hostPath:
    path: /site
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound